Now, each one must create a valid .github/workflows/ci.yml file, and push it. The workflow should:

  Prepare a Linux virtual environment
  Install Java at the appropriate version
  Run Gradle making sure the build works on the reference machine
  If the procedure has been performed correctly, a workflow will will start and complete successfully.

name: CI
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
    pull_request:
    workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build